<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Dell-PC" name="com.crm.qa.testcases.HomePageTest" tests="5" failures="0" timestamp="27 Aug 2018 12:38:32 GMT" time="0.013" errors="1">
  <testcase name="setup" time="0.013" classname="com.crm.qa.testcases.HomePageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.crm.qa.base.TestBase.initialization(TestBase.java:37)
at com.crm.qa.testcases.HomePageTest.setup(HomePageTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase name="verifyhomePageTitleTest" time="0.000" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyhomePageTitleTest -->
  <testcase name="verifyUserName" time="0.000" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyUserName -->
  <testcase name="verifyClickOnContactsLink" time="0.000" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyClickOnContactsLink -->
  <testcase name="verifyClickonDealsLink" time="0.000" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyClickonDealsLink -->
</testsuite> <!-- com.crm.qa.testcases.HomePageTest -->
